import { ZoneType } from './enums/zone-type.enum.js';
import { NpcQuestType } from './enums/npc-quest-type.enum.js';

export interface QuestTemplate {
  id: string;
  zoneType: ZoneType;
  questType: NpcQuestType;
  npcId: string;
  npcName: string;
  title: string;
  description: string;
  requirements: string;
  xpReward: number;
  cooldownDays: number;
}

export const QUEST_TEMPLATES: QuestTemplate[] = [
  // ─── TAVERNE – täglich ───────────────────────────────────────────
  {
    id: 'tav_d_1',
    zoneType: ZoneType.TAVERNE,
    questType: NpcQuestType.DAILY,
    npcId: 'wirt',
    npcName: 'Wirt Gottfried',
    title: 'Frische Luft für den Appetit',
    description: 'Gottfried schickt dich hinaus. Ein kleiner Spaziergang macht den Kopf frei und den Magen leer.',
    requirements: '1.500 Schritte gehen oder 15 Minuten spazieren',
    xpReward: 150,
    cooldownDays: 1,
  },
  {
    id: 'tav_d_2',
    zoneType: ZoneType.TAVERNE,
    questType: NpcQuestType.DAILY,
    npcId: 'wirt',
    npcName: 'Wirt Gottfried',
    title: 'Ein Krug für die Gesundheit',
    description: 'Der Wirt besteht darauf: Heute mindestens 2 Liter Wasser trinken. Sein bestes Bier gibt es erst danach.',
    requirements: '2 Liter Wasser trinken',
    xpReward: 120,
    cooldownDays: 1,
  },
  {
    id: 'tav_d_3',
    zoneType: ZoneType.TAVERNE,
    questType: NpcQuestType.DAILY,
    npcId: 'barde',
    npcName: 'Barde Silvio',
    title: 'Ein Lied für die Seele',
    description: 'Silvio hat dich inspiriert. Übe heute 20 Minuten eine Fertigkeit oder lerne etwas Neues.',
    requirements: '20 Minuten etwas Neues lernen oder üben',
    xpReward: 140,
    cooldownDays: 1,
  },
  {
    id: 'tav_d_4',
    zoneType: ZoneType.TAVERNE,
    questType: NpcQuestType.DAILY,
    npcId: 'barde',
    npcName: 'Barde Silvio',
    title: 'Geschichten aus der Stadt',
    description: 'Der Barde sammelt Geschichten. Führe heute ein echtes Gespräch mit jemandem, den du nicht gut kennst.',
    requirements: 'Ein echtes Gespräch mit einem Fremden führen',
    xpReward: 130,
    cooldownDays: 1,
  },
  // ─── TAVERNE – wöchentlich ────────────────────────────────────────
  {
    id: 'tav_w_1',
    zoneType: ZoneType.TAVERNE,
    questType: NpcQuestType.WEEKLY,
    npcId: 'questgeberin',
    npcName: 'Abenteurerin Mira',
    title: 'Die große Wanderung',
    description: 'Mira schickt dich auf eine richtige Tour. Komme erst wieder, wenn du 10.000 Schritte am Stück gegangen bist.',
    requirements: '10.000 Schritte in einem Zug gehen',
    xpReward: 800,
    cooldownDays: 7,
  },
  {
    id: 'tav_w_2',
    zoneType: ZoneType.TAVERNE,
    questType: NpcQuestType.WEEKLY,
    npcId: 'questgeberin',
    npcName: 'Abenteurerin Mira',
    title: 'Der soziale Krieger',
    description: 'Diese Woche: Triff dich wirklich mit Freunden oder Familie. Kein Chat, kein Video-Call.',
    requirements: 'Echtes Treffen mit Freunden oder Familie organisieren',
    xpReward: 700,
    cooldownDays: 7,
  },
  {
    id: 'tav_w_3',
    zoneType: ZoneType.TAVERNE,
    questType: NpcQuestType.WEEKLY,
    npcId: 'questgeberin',
    npcName: 'Abenteurerin Mira',
    title: 'Meister der Küche',
    description: 'Koche diese Woche eine gesunde Mahlzeit von Grund auf – kein Fertigessen!',
    requirements: 'Eine gesunde Mahlzeit selbst kochen',
    xpReward: 600,
    cooldownDays: 7,
  },
  // ─── ARENA – täglich ─────────────────────────────────────────────
  {
    id: 'arena_d_1',
    zoneType: ZoneType.ARENA,
    questType: NpcQuestType.DAILY,
    npcId: 'trainer',
    npcName: 'Trainer Björn',
    title: 'Morgentraining',
    description: 'Björn brüllt: "20 Minuten Sport. Keine Ausreden. Los!" Du weißt, dass er recht hat.',
    requirements: '20 Minuten Sport treiben',
    xpReward: 180,
    cooldownDays: 1,
  },
  {
    id: 'arena_d_2',
    zoneType: ZoneType.ARENA,
    questType: NpcQuestType.DAILY,
    npcId: 'trainer',
    npcName: 'Trainer Björn',
    title: 'Dehn-Ritual',
    description: 'Der Trainer erklärt: 10 Minuten Dehnen hält den Körper jung. Mach es täglich.',
    requirements: '10 Minuten dehnen oder Yoga',
    xpReward: 100,
    cooldownDays: 1,
  },
  {
    id: 'arena_d_3',
    zoneType: ZoneType.ARENA,
    questType: NpcQuestType.DAILY,
    npcId: 'kampfmeisterin',
    npcName: 'Kampfmeisterin Zara',
    title: 'Stahl und Schweiß',
    description: 'Zara fordert dich heraus: 30 Minuten Krafttraining oder Cardio. Wer aufgibt, ist schwach.',
    requirements: '30 Minuten intensives Training',
    xpReward: 200,
    cooldownDays: 1,
  },
  // ─── ARENA – wöchentlich ─────────────────────────────────────────
  {
    id: 'arena_w_1',
    zoneType: ZoneType.ARENA,
    questType: NpcQuestType.WEEKLY,
    npcId: 'kampfmeisterin',
    npcName: 'Kampfmeisterin Zara',
    title: 'Das Wochenturnier',
    description: 'Zara verlangt Disziplin: Treibe an 4 von 7 Tagen dieser Woche Sport. Dann darfst du dich Krieger nennen.',
    requirements: 'An 4 Tagen diese Woche Sport treiben',
    xpReward: 1000,
    cooldownDays: 7,
  },
  {
    id: 'arena_w_2',
    zoneType: ZoneType.ARENA,
    questType: NpcQuestType.WEEKLY,
    npcId: 'kampfmeisterin',
    npcName: 'Kampfmeisterin Zara',
    title: 'Der Ausdauer-Test',
    description: 'Laufe diese Woche 5 km am Stück oder gehe insgesamt 50.000 Schritte. Zara beobachtet dich.',
    requirements: '5 km laufen oder 50.000 Schritte gehen',
    xpReward: 900,
    cooldownDays: 7,
  },
  // ─── BIBLIOTHEK – täglich ─────────────────────────────────────────
  {
    id: 'bib_d_1',
    zoneType: ZoneType.BIBLIOTHEK,
    questType: NpcQuestType.DAILY,
    npcId: 'bibliothekar',
    npcName: 'Bibliothekar Elias',
    title: 'Tägliche Lektüre',
    description: 'Elias hält dir ein Buch entgegen: "20 Minuten lesen. Täglich. Wähle weise."',
    requirements: '20 Minuten lesen (Buch, Fachartikel)',
    xpReward: 130,
    cooldownDays: 1,
  },
  {
    id: 'bib_d_2',
    zoneType: ZoneType.BIBLIOTHEK,
    questType: NpcQuestType.DAILY,
    npcId: 'bibliothekar',
    npcName: 'Bibliothekar Elias',
    title: 'Das digitale Fasten',
    description: 'Elias möchte, dass du heute 1 Stunde lang dein Smartphone weglegst. Einfach so.',
    requirements: '1 Stunde ohne Smartphone',
    xpReward: 140,
    cooldownDays: 1,
  },
  {
    id: 'bib_d_3',
    zoneType: ZoneType.BIBLIOTHEK,
    questType: NpcQuestType.DAILY,
    npcId: 'lehrerin',
    npcName: 'Lehrerin Nadia',
    title: 'Neues Wissen',
    description: 'Nadia fordert dich auf: Lerne heute etwas komplett Neues – Tutorial, Podcast oder Buch.',
    requirements: '30 Minuten etwas Neues lernen',
    xpReward: 150,
    cooldownDays: 1,
  },
  // ─── BIBLIOTHEK – wöchentlich ─────────────────────────────────────
  {
    id: 'bib_w_1',
    zoneType: ZoneType.BIBLIOTHEK,
    questType: NpcQuestType.WEEKLY,
    npcId: 'lehrerin',
    npcName: 'Lehrerin Nadia',
    title: 'Halbiertes Buch',
    description: 'Lies diese Woche mindestens 50 Seiten in einem Buch deiner Wahl. Kein Hörbuch!',
    requirements: '50 Seiten lesen',
    xpReward: 650,
    cooldownDays: 7,
  },
  {
    id: 'bib_w_2',
    zoneType: ZoneType.BIBLIOTHEK,
    questType: NpcQuestType.WEEKLY,
    npcId: 'lehrerin',
    npcName: 'Lehrerin Nadia',
    title: 'Das Kreativ-Projekt',
    description: 'Arbeite diese Woche 2 Stunden an einem kreativen oder lehrreichen persönlichen Projekt.',
    requirements: '2 Stunden an eigenem Projekt arbeiten',
    xpReward: 750,
    cooldownDays: 7,
  },
  // ─── TEMPEL – täglich ────────────────────────────────────────────
  {
    id: 'tem_d_1',
    zoneType: ZoneType.TEMPEL,
    questType: NpcQuestType.DAILY,
    npcId: 'priester',
    npcName: 'Priester Benedikt',
    title: 'Morgenmeditation',
    description: 'Benedikt zeigt dir: 10 Minuten Stille am Morgen verändern den ganzen Tag.',
    requirements: '10 Minuten meditieren oder Atemübungen',
    xpReward: 120,
    cooldownDays: 1,
  },
  {
    id: 'tem_d_2',
    zoneType: ZoneType.TEMPEL,
    questType: NpcQuestType.DAILY,
    npcId: 'priester',
    npcName: 'Priester Benedikt',
    title: 'Dankbarkeit',
    description: 'Schreibe heute 3 Dinge auf, für die du wirklich dankbar bist. Nicht tippen – mit der Hand.',
    requirements: '3 Dinge handschriftlich aufschreiben',
    xpReward: 100,
    cooldownDays: 1,
  },
  {
    id: 'tem_d_3',
    zoneType: ZoneType.TEMPEL,
    questType: NpcQuestType.DAILY,
    npcId: 'seherin',
    npcName: 'Seherin Lyra',
    title: 'Das Schlaf-Ritual',
    description: 'Lyra flüstert: "Schlaf ist die stärkste Medizin." Heute: 8 Stunden, keine Bildschirme eine Stunde vorher.',
    requirements: '8 Stunden schlafen (Bildschirm 1h vorher weg)',
    xpReward: 110,
    cooldownDays: 1,
  },
  // ─── TEMPEL – wöchentlich ─────────────────────────────────────────
  {
    id: 'tem_w_1',
    zoneType: ZoneType.TEMPEL,
    questType: NpcQuestType.WEEKLY,
    npcId: 'seherin',
    npcName: 'Seherin Lyra',
    title: 'Die stille Woche',
    description: 'Meditiere diese Woche an 5 Tagen je 10 Minuten. Lyra sieht, ob du es wirklich tust.',
    requirements: 'An 5 Tagen je 10 Minuten meditieren',
    xpReward: 700,
    cooldownDays: 7,
  },
  {
    id: 'tem_w_2',
    zoneType: ZoneType.TEMPEL,
    questType: NpcQuestType.WEEKLY,
    npcId: 'seherin',
    npcName: 'Seherin Lyra',
    title: 'Der digitale Detox',
    description: 'Reduziere Social Media diese Woche auf maximal 30 Minuten pro Tag. Lyra prüft deine Seele.',
    requirements: 'Social Media auf max. 30 min/Tag reduzieren',
    xpReward: 800,
    cooldownDays: 7,
  },
];
