import { Category } from '../../quest/enums/category.enum.js';
import { Difficulty } from '../../quest/enums/difficulty.enum.js';
import {
  BonusTrigger,
  Metric,
  ObjectiveKind,
  TrackKind,
} from '../enums/track.enums.js';
import type { BonusRule, Objective } from '../schemas/track.schema.js';

/**
 * The challenge catalog — the seed data behind the quest pool.
 *
 * A challenge is authored here as plain data and never as code: the progress
 * engine reads `kind`/`metric`/`target` off each objective, so adding a
 * challenge is adding an entry, not a branch. Keep entries in the same voice as
 * the daily templates: German, concrete, and doable by an actual teenager on an
 * ordinary Tuesday.
 */
export interface ChallengeDef {
  kind: typeof TrackKind.CHALLENGE;
  slug: string;
  title: string;
  tagline: string;
  description: string;
  emoji: string;
  color: string;
  category: Category;
  difficulty: Difficulty;
  objectives: Objective[];
  bonusRules: BonusRule[];
  completionXp: number;
  completionCoins: number;
  emblemKey: string;
  durationDays: number | null;
  featuredRank: number;
  tags: string[];
  swappableObjectiveIds: string[];
  relapseMetric: Metric | null;
  relapseCopy: string | null;
}

/** Objective builder — keeps the catalog readable by defaulting the noise. */
function obj(o: {
  id: string;
  title: string;
  description: string;
  emoji: string;
  kind: ObjectiveKind;
  metric: Metric;
  target: number;
  xp: number;
  resetOn?: Metric;
  optional?: boolean;
  step?: number;
}): Objective {
  return {
    id: o.id,
    title: o.title,
    description: o.description,
    emoji: o.emoji,
    kind: o.kind,
    metric: o.metric,
    target: o.target,
    xpReward: o.xp,
    resetOn: o.resetOn ?? null,
    optional: o.optional ?? false,
    unlocksAtStep: o.step ?? null,
  };
}

/** Bonus builder. */
function bonus(
  id: string,
  label: string,
  trigger: BonusTrigger,
  value: number,
  flatXp: number,
  multiplier = 1,
): BonusRule {
  return { id, label, trigger, value, flatXp, multiplier };
}

/** Bonuses nearly every habit challenge wants. */
const HABIT_BONUSES: BonusRule[] = [
  bonus(
    'b_week_streak',
    'Eine Woche am Stück',
    BonusTrigger.STREAK_AT_LEAST,
    7,
    50,
    1.25,
  ),
  bonus(
    'b_month_streak',
    'Einen Monat durchgezogen',
    BonusTrigger.STREAK_AT_LEAST,
    30,
    250,
    1.5,
  ),
  bonus('b_perfect', 'Alles mitgenommen', BonusTrigger.PERFECT_RUN, 1, 200),
];

export const CHALLENGE_CATALOG: ChallengeDef[] = [
  // ── 1. Rauchfrei ──────────────────────────────────────────────────────────
  {
    kind: TrackKind.CHALLENGE,
    slug: 'ch_quit_smoking',
    title: 'Rauchfrei werden',
    tagline: 'Jeder Tag ohne zählt. Auch der nach einem Rückfall.',
    description:
      'Die Challenge misst nicht, ob du perfekt bist, sondern wie lange du durchhältst. ' +
      'Jeder rauchfreie Tag verlängert deine Streak. Ein Rückfall setzt sie zurück — ' +
      'dein Rekord bleibt trotzdem stehen, und du fängst nicht bei null an, sondern beim Wissen, ' +
      'dass du es schon mal geschafft hast. Bewegung hilft nachweislich gegen das Verlangen, ' +
      'deshalb zahlen Joggen und Workouts hier mit ein.',
    emoji: '🚭',
    color: '#10b981',
    category: Category.SKILL,
    difficulty: Difficulty.HARD,
    objectives: [
      obj({
        id: 'o_day_one',
        title: 'Der erste Tag',
        description: 'Einen kompletten Tag nicht rauchen. Der schwerste von allen.',
        emoji: '1️⃣',
        kind: ObjectiveKind.SINGLE,
        metric: Metric.SMOKE_FREE_DAY,
        target: 1,
        xp: 100,
      }),
      obj({
        id: 'o_streak_3',
        title: 'Drei am Stück',
        description: 'Drei rauchfreie Tage hintereinander — ab hier lässt der körperliche Entzug nach.',
        emoji: '3️⃣',
        kind: ObjectiveKind.STREAK,
        metric: Metric.SMOKE_FREE_DAY,
        target: 3,
        xp: 200,
        resetOn: Metric.SMOKED,
      }),
      obj({
        id: 'o_streak_7',
        title: 'Die erste Woche',
        description: 'Sieben Tage in Folge. Die Woche, an der die meisten scheitern.',
        emoji: '📅',
        kind: ObjectiveKind.STREAK,
        metric: Metric.SMOKE_FREE_DAY,
        target: 7,
        xp: 400,
        resetOn: Metric.SMOKED,
      }),
      obj({
        id: 'o_streak_30',
        title: 'Ein Monat',
        description: '30 Tage am Stück. Ab hier bist du kein Raucher mehr, der pausiert.',
        emoji: '🏆',
        kind: ObjectiveKind.STREAK,
        metric: Metric.SMOKE_FREE_DAY,
        target: 30,
        xp: 1200,
        resetOn: Metric.SMOKED,
      }),
      obj({
        id: 'o_run_support',
        title: 'Lauf gegen das Verlangen',
        description:
          'Geh fünfmal joggen oder trainieren. Zählt auch, wenn du es unabhängig von dieser Challenge machst.',
        emoji: '🏃',
        kind: ObjectiveKind.TALLY,
        metric: Metric.WORKOUT,
        target: 5,
        xp: 150,
        optional: true,
      }),
      obj({
        id: 'o_money_saved',
        title: 'Was übrig bleibt',
        description: 'Leg 50 € zur Seite, die sonst verraucht wären.',
        emoji: '💶',
        kind: ObjectiveKind.THRESHOLD,
        metric: Metric.MONEY_SAVED,
        target: 50,
        xp: 200,
        optional: true,
      }),
    ],
    bonusRules: [
      ...HABIT_BONUSES,
      bonus(
        'b_smoke_long_run',
        'Zehn Kilometer statt einer Zigarette',
        BonusTrigger.VALUE_AT_LEAST,
        10,
        150,
      ),
    ],
    completionXp: 2000,
    completionCoins: 300,
    emblemKey: 'ach_track_quit_smoking',
    durationDays: null,
    featuredRank: 100,
    tags: ['hype', 'gesundheit', 'streak'],
    swappableObjectiveIds: ['o_run_support'],
    relapseMetric: Metric.SMOKED,
    relapseCopy:
      'Passiert. Deine Streak fängt neu an, dein Rekord bleibt. ' +
      'Rückfälle sind Teil des Aufhörens, nicht das Ende davon.',
  },

  // ── 2. Ausbildungsplatz ───────────────────────────────────────────────────
  {
    kind: TrackKind.CHALLENGE,
    slug: 'ch_apprenticeship',
    title: 'Ausbildungsplatz finden',
    tagline: 'Jede Bewerbung bringt dich näher. Auch die abgelehnten.',
    description:
      'Bewerben ist ein Zahlenspiel und ein Nervenspiel zugleich. Diese Challenge belohnt ' +
      'das, was du steuern kannst: rausschicken, dranbleiben, hingehen. Jede Bewerbung zählt, ' +
      'jedes Gespräch zählt deutlich mehr, und der unterschriebene Vertrag beendet die Challenge.',
    emoji: '📋',
    color: '#3b82f6',
    category: Category.SKILL,
    difficulty: Difficulty.MEDIUM,
    objectives: [
      obj({
        id: 'o_first_application',
        title: 'Die erste raus',
        description: 'Schick deine erste Bewerbung ab. Angefangen ist halb geschafft.',
        emoji: '✉️',
        kind: ObjectiveKind.SINGLE,
        metric: Metric.JOB_APPLICATION,
        target: 1,
        xp: 150,
      }),
      obj({
        id: 'o_ten_applications',
        title: 'Zehn Bewerbungen',
        description: 'Schick insgesamt zehn Bewerbungen ab.',
        emoji: '📮',
        kind: ObjectiveKind.TALLY,
        metric: Metric.JOB_APPLICATION,
        target: 10,
        xp: 500,
      }),
      obj({
        id: 'o_application_streak',
        title: 'Dranbleiben',
        description: 'An fünf Tagen hintereinander mindestens eine Bewerbung rausschicken.',
        emoji: '🔥',
        kind: ObjectiveKind.STREAK,
        metric: Metric.JOB_APPLICATION,
        target: 5,
        xp: 400,
      }),
      obj({
        id: 'o_interview',
        title: 'Vorstellungsgespräch',
        description: 'Geh zu einem Vorstellungsgespräch. Egal wie es ausgeht — du warst da.',
        emoji: '🤝',
        kind: ObjectiveKind.TALLY,
        metric: Metric.JOB_INTERVIEW,
        target: 1,
        xp: 800,
      }),
      obj({
        id: 'o_three_interviews',
        title: 'Routine im Gespräch',
        description: 'Drei Vorstellungsgespräche geführt. Beim dritten zitterst du weniger.',
        emoji: '🗣️',
        kind: ObjectiveKind.TALLY,
        metric: Metric.JOB_INTERVIEW,
        target: 3,
        xp: 900,
        optional: true,
      }),
      obj({
        id: 'o_offer',
        title: 'Zusage',
        description: 'Einen Ausbildungsvertrag in der Hand halten.',
        emoji: '🎉',
        kind: ObjectiveKind.SINGLE,
        metric: Metric.JOB_OFFER,
        target: 1,
        xp: 2000,
      }),
    ],
    bonusRules: [
      bonus(
        'b_apply_early',
        'Vor 10 Uhr beworben',
        BonusTrigger.BEFORE_HOUR,
        10,
        40,
      ),
      bonus(
        'b_apply_streak',
        'Fünf Tage am Stück beworben',
        BonusTrigger.STREAK_AT_LEAST,
        5,
        100,
        1.25,
      ),
      bonus('b_perfect', 'Alles mitgenommen', BonusTrigger.PERFECT_RUN, 1, 300),
    ],
    completionXp: 2500,
    completionCoins: 400,
    emblemKey: 'ach_track_apprenticeship',
    durationDays: null,
    featuredRank: 95,
    tags: ['zukunft', 'schule', 'ernst'],
    swappableObjectiveIds: [],
    relapseMetric: null,
    relapseCopy: null,
  },

  // ── 3. Schul-Streak ───────────────────────────────────────────────────────
  {
    kind: TrackKind.CHALLENGE,
    slug: 'ch_school_streak',
    title: 'Schul-Streak',
    tagline: 'Jeden Tag da. Das ist die halbe Miete.',
    description:
      'Anwesenheit ist die langweiligste und wirksamste Sache der Welt. Check jeden Schultag ' +
      'ein — per GPS an der Schule oder von Hand — und bau eine Streak auf, die über Wochen läuft. ' +
      'Ferien und Wochenenden brechen sie nicht.',
    emoji: '🎒',
    color: '#f59e0b',
    category: Category.SKILL,
    difficulty: Difficulty.MEDIUM,
    objectives: [
      obj({
        id: 'o_week_school',
        title: 'Eine volle Woche',
        description: 'Fünf Schultage in Folge anwesend.',
        emoji: '5️⃣',
        kind: ObjectiveKind.STREAK,
        metric: Metric.SCHOOL_ATTENDANCE,
        target: 5,
        xp: 300,
      }),
      obj({
        id: 'o_month_school',
        title: 'Ein ganzer Monat',
        description: '20 Schultage in Folge. Kein Schwänzen, kein Verschlafen.',
        emoji: '📆',
        kind: ObjectiveKind.STREAK,
        metric: Metric.SCHOOL_ATTENDANCE,
        target: 20,
        xp: 1000,
      }),
      obj({
        id: 'o_study_sessions',
        title: 'Nachmittags noch was tun',
        description: 'Insgesamt 600 Minuten lernen oder Hausaufgaben machen.',
        emoji: '📚',
        kind: ObjectiveKind.THRESHOLD,
        metric: Metric.STUDY_MINUTES,
        target: 600,
        xp: 500,
        optional: true,
      }),
      obj({
        id: 'o_early_school',
        title: 'Ohne Hetze',
        description: 'An zehn Tagen vor 7 Uhr aufstehen.',
        emoji: '⏰',
        kind: ObjectiveKind.UNIQUE_DAYS,
        metric: Metric.EARLY_RISE,
        target: 10,
        xp: 400,
        optional: true,
      }),
    ],
    bonusRules: [
      ...HABIT_BONUSES,
      bonus('b_school_early', 'Vor 8 Uhr eingecheckt', BonusTrigger.BEFORE_HOUR, 8, 20),
    ],
    completionXp: 1500,
    completionCoins: 200,
    emblemKey: 'ach_track_school_streak',
    durationDays: null,
    featuredRank: 90,
    tags: ['schule', 'streak', 'alltag'],
    swappableObjectiveIds: [],
    relapseMetric: null,
    relapseCopy: null,
  },

  // ── 4. Route-Streak ───────────────────────────────────────────────────────
  {
    kind: TrackKind.CHALLENGE,
    slug: 'ch_route_streak',
    title: 'Täglich unterwegs',
    tagline: 'Jeden Tag mindestens eine Route. Egal wie kurz.',
    description:
      'Kombiniert direkt mit den Route-SideQuests: Jeder Tag, an dem du mindestens einen ' +
      'Kilometer zu Fuß oder mit dem Rad zurücklegst, verlängert die Streak. Die App misst das ' +
      'automatisch mit, während du unterwegs bist.',
    emoji: '🧭',
    color: '#22c55e',
    category: Category.SPORT,
    difficulty: Difficulty.EASY,
    objectives: [
      obj({
        id: 'o_route_streak_7',
        title: 'Sieben Tage unterwegs',
        description: 'An sieben Tagen hintereinander eine Route laufen.',
        emoji: '🔥',
        kind: ObjectiveKind.STREAK,
        metric: Metric.ROUTE_COMPLETED,
        target: 7,
        xp: 400,
      }),
      obj({
        id: 'o_route_streak_30',
        title: 'Dreißig Tage unterwegs',
        description: 'Einen ganzen Monat lang jeden Tag raus.',
        emoji: '🏆',
        kind: ObjectiveKind.STREAK,
        metric: Metric.ROUTE_COMPLETED,
        target: 30,
        xp: 1500,
      }),
      obj({
        id: 'o_total_km',
        title: 'Hundert Kilometer',
        description: 'Leg insgesamt 100 km zurück.',
        emoji: '📏',
        kind: ObjectiveKind.THRESHOLD,
        metric: Metric.ROUTE_DISTANCE_KM,
        target: 100,
        xp: 800,
      }),
      obj({
        id: 'o_long_route',
        title: 'Die lange Runde',
        description: 'Eine einzelne Route über 10 km.',
        emoji: '🥾',
        kind: ObjectiveKind.PEAK,
        metric: Metric.ROUTE_DISTANCE_KM,
        target: 10,
        xp: 300,
        optional: true,
      }),
    ],
    bonusRules: [
      ...HABIT_BONUSES,
      bonus('b_long_run', 'Über 10 km am Stück', BonusTrigger.VALUE_AT_LEAST, 10, 120),
      bonus('b_weekend_route', 'Auch am Wochenende', BonusTrigger.WEEKEND, 1, 30),
      bonus('b_cold_route', 'Bei unter 5 °C raus', BonusTrigger.COLD_WEATHER, 5, 60),
    ],
    completionXp: 1800,
    completionCoins: 250,
    emblemKey: 'ach_track_route_streak',
    durationDays: null,
    featuredRank: 88,
    tags: ['sport', 'streak', 'draußen'],
    swappableObjectiveIds: [],
    relapseMetric: null,
    relapseCopy: null,
  },

  // ── 5.–24. Die Hype-Challenges ────────────────────────────────────────────
  {
    kind: TrackKind.CHALLENGE,
    slug: 'ch_75_soft',
    title: '75 Soft',
    tagline: 'Die machbare Version der Internet-Challenge.',
    description:
      '75 Tage: jeden Tag Sport, jeden Tag lesen, jeden Tag genug Wasser, kein Alkohol. ' +
      'Die entschärfte Fassung von 75 Hard — ohne zwei Workouts am Tag und ohne Neustart bei jedem Ausrutscher.',
    emoji: '💪',
    color: '#ef4444',
    category: Category.SPORT,
    difficulty: Difficulty.HARD,
    objectives: [
      obj({
        id: 'o_75_workout',
        title: '75 Tage Sport',
        description: 'An 75 Tagen mindestens 45 Minuten bewegen.',
        emoji: '🏋️',
        kind: ObjectiveKind.UNIQUE_DAYS,
        metric: Metric.WORKOUT,
        target: 75,
        xp: 2000,
      }),
      obj({
        id: 'o_75_read',
        title: '750 Seiten',
        description: 'Zehn Seiten am Tag, 75 Tage lang.',
        emoji: '📖',
        kind: ObjectiveKind.THRESHOLD,
        metric: Metric.PAGES_READ,
        target: 750,
        xp: 1000,
      }),
      obj({
        id: 'o_75_water',
        title: '75 Tage genug getrunken',
        description: 'An 75 Tagen dein Wasserziel erreichen.',
        emoji: '💧',
        kind: ObjectiveKind.UNIQUE_DAYS,
        metric: Metric.HYDRATION_DAY,
        target: 75,
        xp: 800,
      }),
      obj({
        id: 'o_75_sober',
        title: '75 Tage nüchtern',
        description: 'Kein Alkohol, 75 Tage lang.',
        emoji: '🚫',
        kind: ObjectiveKind.STREAK,
        metric: Metric.ALCOHOL_FREE_DAY,
        target: 75,
        xp: 1500,
      }),
    ],
    bonusRules: HABIT_BONUSES,
    completionXp: 5000,
    completionCoins: 750,
    emblemKey: 'ach_track_75_soft',
    durationDays: 90,
    featuredRank: 99,
    tags: ['hype', 'fitness', 'hart'],
    swappableObjectiveIds: ['o_75_workout'],
    relapseMetric: null,
    relapseCopy: null,
  },
  {
    kind: TrackKind.CHALLENGE,
    slug: 'ch_cold_shower',
    title: 'Kalt duschen',
    tagline: '30 Tage. Die ersten zehn Sekunden sind die Hölle.',
    description:
      'Jeden Morgen die letzten 30 Sekunden kalt. Klingt nach nichts, fühlt sich nach allem an — ' +
      'und ist die billigste Mutprobe, die es gibt.',
    emoji: '🚿',
    color: '#06b6d4',
    category: Category.ADVENTURE,
    difficulty: Difficulty.MEDIUM,
    objectives: [
      obj({
        id: 'o_cold_7',
        title: 'Erste Woche kalt',
        description: 'Sieben Tage hintereinander kalt duschen.',
        emoji: '❄️',
        kind: ObjectiveKind.STREAK,
        metric: Metric.COLD_SHOWER,
        target: 7,
        xp: 300,
      }),
      obj({
        id: 'o_cold_30',
        title: 'Dreißig Tage kalt',
        description: 'Einen ganzen Monat durchziehen.',
        emoji: '🧊',
        kind: ObjectiveKind.STREAK,
        metric: Metric.COLD_SHOWER,
        target: 30,
        xp: 1200,
      }),
    ],
    bonusRules: [
      ...HABIT_BONUSES,
      bonus('b_cold_early', 'Vor 7 Uhr kalt geduscht', BonusTrigger.BEFORE_HOUR, 7, 25),
    ],
    completionXp: 1200,
    completionCoins: 180,
    emblemKey: 'ach_track_cold_shower',
    durationDays: 45,
    featuredRank: 85,
    tags: ['hype', 'mutprobe', 'streak'],
    swappableObjectiveIds: [],
    relapseMetric: null,
    relapseCopy: null,
  },
  {
    kind: TrackKind.CHALLENGE,
    slug: 'ch_5am_club',
    title: '5-Uhr-Club',
    tagline: 'Aufstehen, bevor die Welt was von dir will.',
    description:
      'Drei Wochen lang vor sechs aufstehen. Der Trick ist nicht der Wecker, sondern was du ' +
      'in der stillen Stunde davor machst.',
    emoji: '🌅',
    color: '#f97316',
    category: Category.SKILL,
    difficulty: Difficulty.HARD,
    objectives: [
      obj({
        id: 'o_rise_7',
        title: 'Sieben frühe Tage',
        description: 'Eine Woche lang vor 6 Uhr aufstehen.',
        emoji: '⏰',
        kind: ObjectiveKind.STREAK,
        metric: Metric.EARLY_RISE,
        target: 7,
        xp: 400,
      }),
      obj({
        id: 'o_rise_21',
        title: 'Einundzwanzig Tage',
        description: 'Drei Wochen — so lange dauert es, bis es normal wird.',
        emoji: '🐓',
        kind: ObjectiveKind.STREAK,
        metric: Metric.EARLY_RISE,
        target: 21,
        xp: 1200,
      }),
      obj({
        id: 'o_rise_sleep',
        title: 'Auch rechtzeitig ins Bett',
        description: 'An 15 Tagen zur geplanten Zeit schlafen gehen.',
        emoji: '🛏️',
        kind: ObjectiveKind.UNIQUE_DAYS,
        metric: Metric.SLEEP_ON_TIME,
        target: 15,
        xp: 500,
        optional: true,
      }),
    ],
    bonusRules: HABIT_BONUSES,
    completionXp: 1600,
    completionCoins: 220,
    emblemKey: 'ach_track_5am_club',
    durationDays: 40,
    featuredRank: 84,
    tags: ['hype', 'disziplin', 'streak'],
    swappableObjectiveIds: [],
    relapseMetric: null,
    relapseCopy: null,
  },
  {
    kind: TrackKind.CHALLENGE,
    slug: 'ch_digital_detox',
    title: 'Digital Detox',
    tagline: 'Weniger Bildschirm, mehr Leben.',
    description:
      'Setz dir ein tägliches Bildschirmlimit und halt es. Dazu Tage ganz ohne Social Media — ' +
      'und was du mit der freien Zeit machst, ist der eigentliche Gewinn.',
    emoji: '📵',
    color: '#8b5cf6',
    category: Category.SKILL,
    difficulty: Difficulty.MEDIUM,
    objectives: [
      obj({
        id: 'o_screen_14',
        title: 'Vierzehn Tage im Limit',
        description: 'An 14 Tagen unter deinem Bildschirmlimit bleiben.',
        emoji: '📱',
        kind: ObjectiveKind.UNIQUE_DAYS,
        metric: Metric.SCREEN_LIMIT_KEPT,
        target: 14,
        xp: 600,
      }),
      obj({
        id: 'o_screen_streak',
        title: 'Zehn Tage am Stück',
        description: 'Zehn Tage hintereinander das Limit halten.',
        emoji: '🔥',
        kind: ObjectiveKind.STREAK,
        metric: Metric.SCREEN_LIMIT_KEPT,
        target: 10,
        xp: 700,
      }),
      obj({
        id: 'o_screen_replace',
        title: 'Was Besseres gemacht',
        description: 'Zehnmal stattdessen etwas erschaffen: gezeichnet, gefilmt, geschrieben.',
        emoji: '🎨',
        kind: ObjectiveKind.TALLY,
        metric: Metric.CREATION_MADE,
        target: 10,
        xp: 500,
        optional: true,
      }),
    ],
    bonusRules: HABIT_BONUSES,
    completionXp: 1400,
    completionCoins: 200,
    emblemKey: 'ach_track_digital_detox',
    durationDays: 30,
    featuredRank: 92,
    tags: ['hype', 'kopf', 'streak'],
    swappableObjectiveIds: [],
    relapseMetric: null,
    relapseCopy: null,
  },
  {
    kind: TrackKind.CHALLENGE,
    slug: 'ch_no_spend',
    title: 'No-Spend-Monat',
    tagline: 'Einen Monat nichts Unnötiges kaufen.',
    description:
      'Kein Lieferdienst, keine Impulskäufe, kein "war halt reduziert". Was du nicht ausgibst, ' +
      'wanderst du aufs Sparziel — und siehst am Ende schwarz auf weiß, was so ein Monat wert ist.',
    emoji: '🐷',
    color: '#ec4899',
    category: Category.SKILL,
    difficulty: Difficulty.MEDIUM,
    objectives: [
      obj({
        id: 'o_nospend_20',
        title: 'Zwanzig sparsame Tage',
        description: 'An 20 Tagen nichts Unnötiges kaufen.',
        emoji: '🚫',
        kind: ObjectiveKind.UNIQUE_DAYS,
        metric: Metric.NO_SPEND_DAY,
        target: 20,
        xp: 700,
      }),
      obj({
        id: 'o_save_100',
        title: 'Hundert Euro zurückgelegt',
        description: 'Insgesamt 100 € sparen.',
        emoji: '💰',
        kind: ObjectiveKind.THRESHOLD,
        metric: Metric.MONEY_SAVED,
        target: 100,
        xp: 800,
      }),
      obj({
        id: 'o_cook_instead',
        title: 'Selbst gekocht statt bestellt',
        description: 'Fünfzehnmal selbst kochen.',
        emoji: '🍳',
        kind: ObjectiveKind.TALLY,
        metric: Metric.MEAL_COOKED,
        target: 15,
        xp: 500,
      }),
    ],
    bonusRules: HABIT_BONUSES,
    completionXp: 1600,
    completionCoins: 300,
    emblemKey: 'ach_track_no_spend',
    durationDays: 35,
    featuredRank: 80,
    tags: ['geld', 'alltag', 'hype'],
    swappableObjectiveIds: [],
    relapseMetric: null,
    relapseCopy: null,
  },
  {
    kind: TrackKind.CHALLENGE,
    slug: 'ch_gym_starter',
    title: 'Gym-Starter',
    tagline: 'Zwölf Sessions. Danach gehörst du dazu.',
    description:
      'Die Hürde ist nie das Training, sondern das Hingehen. Zwölf Einheiten in sechs Wochen — ' +
      'danach ist das Studio kein fremder Ort mehr.',
    emoji: '🏋️',
    color: '#64748b',
    category: Category.SPORT,
    difficulty: Difficulty.MEDIUM,
    objectives: [
      obj({
        id: 'o_gym_first',
        title: 'Das erste Mal',
        description: 'Einmal hingehen und wirklich trainieren.',
        emoji: '🚪',
        kind: ObjectiveKind.SINGLE,
        metric: Metric.WORKOUT,
        target: 1,
        xp: 200,
      }),
      obj({
        id: 'o_gym_12',
        title: 'Zwölf Einheiten',
        description: 'Zwölfmal trainieren.',
        emoji: '💪',
        kind: ObjectiveKind.TALLY,
        metric: Metric.WORKOUT,
        target: 12,
        xp: 900,
      }),
      obj({
        id: 'o_gym_rhythm',
        title: 'Im Rhythmus',
        description: 'Drei Wochen hintereinander mindestens eine Einheit.',
        emoji: '📈',
        kind: ObjectiveKind.STREAK,
        metric: Metric.WORKOUT,
        target: 3,
        xp: 400,
        optional: true,
      }),
    ],
    bonusRules: HABIT_BONUSES,
    completionXp: 1300,
    completionCoins: 200,
    emblemKey: 'ach_track_gym_starter',
    durationDays: 42,
    featuredRank: 86,
    tags: ['hype', 'fitness'],
    swappableObjectiveIds: [],
    relapseMetric: null,
    relapseCopy: null,
  },
  {
    kind: TrackKind.CHALLENGE,
    slug: 'ch_couch_to_5k',
    title: 'Couch to 5K',
    tagline: 'Von null auf fünf Kilometer am Stück.',
    description:
      'Der Klassiker: neun Wochen, drei Läufe pro Woche, am Ende fünf Kilometer ohne Gehpause. ' +
      'Die App misst deine Routen automatisch mit.',
    emoji: '🏃',
    color: '#14b8a6',
    category: Category.SPORT,
    difficulty: Difficulty.MEDIUM,
    objectives: [
      obj({
        id: 'o_c25k_first',
        title: 'Erster Lauf',
        description: 'Einmal losgelaufen. Auch mit Gehpausen.',
        emoji: '👟',
        kind: ObjectiveKind.SINGLE,
        metric: Metric.ROUTE_COMPLETED,
        target: 1,
        xp: 150,
      }),
      obj({
        id: 'o_c25k_27',
        title: 'Siebenundzwanzig Läufe',
        description: 'Das komplette Programm: drei Läufe pro Woche, neun Wochen.',
        emoji: '📆',
        kind: ObjectiveKind.TALLY,
        metric: Metric.ROUTE_COMPLETED,
        target: 27,
        xp: 1200,
      }),
      obj({
        id: 'o_c25k_5k',
        title: 'Die fünf Kilometer',
        description: 'Eine einzelne Route über 5 km.',
        emoji: '🏅',
        kind: ObjectiveKind.PEAK,
        metric: Metric.ROUTE_DISTANCE_KM,
        target: 5,
        xp: 1000,
      }),
    ],
    bonusRules: [
      ...HABIT_BONUSES,
      bonus('b_c25k_long', 'Über 8 km gelaufen', BonusTrigger.VALUE_AT_LEAST, 8, 150),
    ],
    completionXp: 2000,
    completionCoins: 300,
    emblemKey: 'ach_track_couch_to_5k',
    durationDays: 70,
    featuredRank: 87,
    tags: ['hype', 'fitness', 'draußen'],
    swappableObjectiveIds: [],
    relapseMetric: null,
    relapseCopy: null,
  },
  {
    kind: TrackKind.CHALLENGE,
    slug: 'ch_10k_steps',
    title: 'Jeden Tag fünf Kilometer',
    tagline: 'Die einfachste Fitness-Challenge, die es gibt.',
    description:
      'Fünf Kilometer am Tag, 30 Tage lang. Kein Studio, keine Ausrüstung, keine Ausrede. ' +
      'Läuft automatisch über die Routenerfassung mit.',
    emoji: '👣',
    color: '#84cc16',
    category: Category.SPORT,
    difficulty: Difficulty.EASY,
    objectives: [
      obj({
        id: 'o_steps_streak',
        title: 'Vierzehn Tage am Stück',
        description: 'Zwei Wochen hintereinander mindestens eine Route.',
        emoji: '🔥',
        kind: ObjectiveKind.STREAK,
        metric: Metric.ROUTE_COMPLETED,
        target: 14,
        xp: 600,
      }),
      obj({
        id: 'o_steps_150',
        title: 'Hundertfünfzig Kilometer',
        description: 'Insgesamt 150 km in 30 Tagen.',
        emoji: '📏',
        kind: ObjectiveKind.THRESHOLD,
        metric: Metric.ROUTE_DISTANCE_KM,
        target: 150,
        xp: 1000,
      }),
    ],
    bonusRules: HABIT_BONUSES,
    completionXp: 1200,
    completionCoins: 180,
    emblemKey: 'ach_track_10k_steps',
    durationDays: 30,
    featuredRank: 82,
    tags: ['fitness', 'streak', 'einfach'],
    swappableObjectiveIds: [],
    relapseMetric: null,
    relapseCopy: null,
  },
  {
    kind: TrackKind.CHALLENGE,
    slug: 'ch_read_book',
    title: 'Ein Buch in einem Monat',
    tagline: 'Zehn Seiten am Tag. Mehr nicht.',
    description:
      'Dreihundert Seiten klingen nach viel. Zehn Seiten am Tag klingen nach nichts. ' +
      'Es ist dasselbe.',
    emoji: '📚',
    color: '#a855f7',
    category: Category.SKILL,
    difficulty: Difficulty.EASY,
    objectives: [
      obj({
        id: 'o_read_300',
        title: 'Dreihundert Seiten',
        description: 'Ein ganzes Buch durchlesen.',
        emoji: '📖',
        kind: ObjectiveKind.THRESHOLD,
        metric: Metric.PAGES_READ,
        target: 300,
        xp: 800,
      }),
      obj({
        id: 'o_read_streak',
        title: 'Vierzehn Leseabende',
        description: 'An 14 Tagen hintereinander lesen.',
        emoji: '🌙',
        kind: ObjectiveKind.STREAK,
        metric: Metric.PAGES_READ,
        target: 14,
        xp: 600,
      }),
    ],
    bonusRules: [
      ...HABIT_BONUSES,
      bonus('b_read_night', 'Nach 22 Uhr gelesen', BonusTrigger.AFTER_HOUR, 22, 20),
    ],
    completionXp: 1000,
    completionCoins: 150,
    emblemKey: 'ach_track_read_book',
    durationDays: 35,
    featuredRank: 78,
    tags: ['kopf', 'streak', 'einfach'],
    swappableObjectiveIds: [],
    relapseMetric: null,
    relapseCopy: null,
  },
  {
    kind: TrackKind.CHALLENGE,
    slug: 'ch_hydration',
    title: 'Wasser-Challenge',
    tagline: 'Zwei Liter am Tag, 21 Tage lang.',
    description:
      'Die Challenge mit dem besten Aufwand-Wirkung-Verhältnis. Nach drei Wochen merkst du ' +
      'den Unterschied an Haut, Kopf und Konzentration.',
    emoji: '💧',
    color: '#0ea5e9',
    category: Category.SPORT,
    difficulty: Difficulty.EASY,
    objectives: [
      obj({
        id: 'o_water_21',
        title: 'Einundzwanzig Tage',
        description: 'Drei Wochen hintereinander dein Wasserziel erreichen.',
        emoji: '🚰',
        kind: ObjectiveKind.STREAK,
        metric: Metric.HYDRATION_DAY,
        target: 21,
        xp: 700,
      }),
    ],
    bonusRules: HABIT_BONUSES,
    completionXp: 700,
    completionCoins: 100,
    emblemKey: 'ach_track_hydration',
    durationDays: 30,
    featuredRank: 70,
    tags: ['gesundheit', 'einfach', 'streak'],
    swappableObjectiveIds: [],
    relapseMetric: null,
    relapseCopy: null,
  },
  {
    kind: TrackKind.CHALLENGE,
    slug: 'ch_sleep_schedule',
    title: 'Schlafrhythmus',
    tagline: 'Jeden Tag zur selben Zeit ins Bett.',
    description:
      'Nicht mehr schlafen — regelmäßiger schlafen. Zwei Wochen dieselbe Uhrzeit, und dein ' +
      'Körper wacht von allein auf.',
    emoji: '🛌',
    color: '#6366f1',
    category: Category.SKILL,
    difficulty: Difficulty.MEDIUM,
    objectives: [
      obj({
        id: 'o_sleep_14',
        title: 'Vierzehn Nächte',
        description: 'Zwei Wochen hintereinander zur geplanten Zeit ins Bett.',
        emoji: '🌜',
        kind: ObjectiveKind.STREAK,
        metric: Metric.SLEEP_ON_TIME,
        target: 14,
        xp: 700,
      }),
      obj({
        id: 'o_sleep_rise',
        title: 'Und früh raus',
        description: 'An zehn Tagen früh aufstehen.',
        emoji: '☀️',
        kind: ObjectiveKind.UNIQUE_DAYS,
        metric: Metric.EARLY_RISE,
        target: 10,
        xp: 400,
        optional: true,
      }),
    ],
    bonusRules: HABIT_BONUSES,
    completionXp: 900,
    completionCoins: 130,
    emblemKey: 'ach_track_sleep_schedule',
    durationDays: 28,
    featuredRank: 74,
    tags: ['gesundheit', 'streak'],
    swappableObjectiveIds: [],
    relapseMetric: null,
    relapseCopy: null,
  },
  {
    kind: TrackKind.CHALLENGE,
    slug: 'ch_meal_prep',
    title: 'Selbst kochen',
    tagline: 'Zwanzig Mahlzeiten statt zwanzig Bestellungen.',
    description:
      'Kochen ist die Fähigkeit mit der besten Rendite: billiger, gesünder, und du beeindruckst ' +
      'damit mehr Leute als mit jedem Lieferdienst.',
    emoji: '🍳',
    color: '#f59e0b',
    category: Category.SKILL,
    difficulty: Difficulty.EASY,
    objectives: [
      obj({
        id: 'o_cook_20',
        title: 'Zwanzig Mahlzeiten',
        description: 'Zwanzigmal selbst kochen.',
        emoji: '🥘',
        kind: ObjectiveKind.TALLY,
        metric: Metric.MEAL_COOKED,
        target: 20,
        xp: 800,
      }),
      obj({
        id: 'o_cook_streak',
        title: 'Sieben Tage am Stück',
        description: 'Eine Woche hintereinander selbst kochen.',
        emoji: '🔥',
        kind: ObjectiveKind.STREAK,
        metric: Metric.MEAL_COOKED,
        target: 7,
        xp: 500,
        optional: true,
      }),
    ],
    bonusRules: HABIT_BONUSES,
    completionXp: 1000,
    completionCoins: 160,
    emblemKey: 'ach_track_meal_prep',
    durationDays: 30,
    featuredRank: 72,
    tags: ['alltag', 'skill'],
    swappableObjectiveIds: [],
    relapseMetric: null,
    relapseCopy: null,
  },
  {
    kind: TrackKind.CHALLENGE,
    slug: 'ch_room_glowup',
    title: 'Zimmer-Glow-Up',
    tagline: 'Vom Chaos zum Ort, an dem du sein willst.',
    description:
      'Dreißig Aufräum- und Putzaktionen, verteilt über einen Monat. Am Ende sieht dein Zimmer ' +
      'aus wie die Vorher-Nachher-Videos — nur echt.',
    emoji: '🧹',
    color: '#22d3ee',
    category: Category.SKILL,
    difficulty: Difficulty.EASY,
    objectives: [
      obj({
        id: 'o_chores_30',
        title: 'Dreißig Aktionen',
        description: 'Dreißigmal aufräumen, putzen oder aussortieren.',
        emoji: '🧽',
        kind: ObjectiveKind.TALLY,
        metric: Metric.CHORE_DONE,
        target: 30,
        xp: 800,
      }),
      obj({
        id: 'o_chores_streak',
        title: 'Zehn Tage am Stück',
        description: 'Zehn Tage hintereinander mindestens eine Sache erledigen.',
        emoji: '🔥',
        kind: ObjectiveKind.STREAK,
        metric: Metric.CHORE_DONE,
        target: 10,
        xp: 500,
      }),
      obj({
        id: 'o_glowup_photo',
        title: 'Vorher-Nachher',
        description: 'Mach ein Foto vom Ergebnis.',
        emoji: '📸',
        kind: ObjectiveKind.SINGLE,
        metric: Metric.CREATION_MADE,
        target: 1,
        xp: 200,
        optional: true,
      }),
    ],
    bonusRules: HABIT_BONUSES,
    completionXp: 1100,
    completionCoins: 170,
    emblemKey: 'ach_track_room_glowup',
    durationDays: 30,
    featuredRank: 83,
    tags: ['hype', 'alltag', 'zuhause'],
    swappableObjectiveIds: [],
    relapseMetric: null,
    relapseCopy: null,
  },
  {
    kind: TrackKind.CHALLENGE,
    slug: 'ch_savings_goal',
    title: 'Sparziel',
    tagline: 'Fünfhundert Euro, Schritt für Schritt.',
    description:
      'Egal wofür — Führerschein, Reise, erste eigene Bude. Jeder Betrag zählt, auch fünf Euro.',
    emoji: '💰',
    color: '#eab308',
    category: Category.SKILL,
    difficulty: Difficulty.MEDIUM,
    objectives: [
      obj({
        id: 'o_save_100_first',
        title: 'Die ersten hundert',
        description: '100 € zusammenhaben.',
        emoji: '💶',
        kind: ObjectiveKind.THRESHOLD,
        metric: Metric.MONEY_SAVED,
        target: 100,
        xp: 400,
      }),
      obj({
        id: 'o_save_500',
        title: 'Fünfhundert Euro',
        description: 'Das volle Sparziel erreichen.',
        emoji: '🏦',
        kind: ObjectiveKind.THRESHOLD,
        metric: Metric.MONEY_SAVED,
        target: 500,
        xp: 1500,
      }),
      obj({
        id: 'o_save_nospend',
        title: 'Sparsame Tage',
        description: 'An 15 Tagen nichts Unnötiges kaufen.',
        emoji: '🚫',
        kind: ObjectiveKind.UNIQUE_DAYS,
        metric: Metric.NO_SPEND_DAY,
        target: 15,
        xp: 600,
        optional: true,
      }),
    ],
    bonusRules: HABIT_BONUSES,
    completionXp: 1800,
    completionCoins: 400,
    emblemKey: 'ach_track_savings_goal',
    durationDays: null,
    featuredRank: 79,
    tags: ['geld', 'zukunft'],
    swappableObjectiveIds: [],
    relapseMetric: null,
    relapseCopy: null,
  },
  {
    kind: TrackKind.CHALLENGE,
    slug: 'ch_creator_sprint',
    title: 'Creator-Sprint',
    tagline: 'Dreißig Tage, dreißig Sachen gemacht.',
    description:
      'Video, Foto, Beat, Zeichnung, Text — egal. Jeden Tag etwas veröffentlichen oder ' +
      'zumindest fertigstellen. Quantität schlägt am Anfang immer Qualität.',
    emoji: '🎬',
    color: '#f43f5e',
    category: Category.SKILL,
    difficulty: Difficulty.MEDIUM,
    objectives: [
      obj({
        id: 'o_create_30',
        title: 'Dreißig Werke',
        description: 'Dreißig Sachen fertigstellen.',
        emoji: '🎨',
        kind: ObjectiveKind.TALLY,
        metric: Metric.CREATION_MADE,
        target: 30,
        xp: 1200,
      }),
      obj({
        id: 'o_create_streak',
        title: 'Vierzehn Tage am Stück',
        description: 'Zwei Wochen hintereinander täglich etwas machen.',
        emoji: '🔥',
        kind: ObjectiveKind.STREAK,
        metric: Metric.CREATION_MADE,
        target: 14,
        xp: 800,
      }),
    ],
    bonusRules: [
      ...HABIT_BONUSES,
      bonus('b_create_night', 'Nachts noch fertig gemacht', BonusTrigger.AFTER_HOUR, 23, 30),
    ],
    completionXp: 1800,
    completionCoins: 280,
    emblemKey: 'ach_track_creator_sprint',
    durationDays: 35,
    featuredRank: 91,
    tags: ['hype', 'kreativ'],
    swappableObjectiveIds: [],
    relapseMetric: null,
    relapseCopy: null,
  },
  {
    kind: TrackKind.CHALLENGE,
    slug: 'ch_language_streak',
    title: 'Sprachen-Streak',
    tagline: 'Zehn Minuten am Tag schlagen zwei Stunden am Sonntag.',
    description:
      'Eine neue Sprache lernt man nicht in Blöcken, sondern in Wiederholungen. ' +
      'Dreißig Tage, jeden Tag ein bisschen.',
    emoji: '🗣️',
    color: '#8b5cf6',
    category: Category.SKILL,
    difficulty: Difficulty.MEDIUM,
    objectives: [
      obj({
        id: 'o_lang_streak_30',
        title: 'Dreißig Tage am Stück',
        description: 'Jeden Tag mindestens zehn Minuten lernen.',
        emoji: '🔥',
        kind: ObjectiveKind.STREAK,
        metric: Metric.STUDY_MINUTES,
        target: 30,
        xp: 1200,
      }),
      obj({
        id: 'o_lang_600',
        title: 'Zehn Stunden',
        description: 'Insgesamt 600 Minuten lernen.',
        emoji: '⏳',
        kind: ObjectiveKind.THRESHOLD,
        metric: Metric.STUDY_MINUTES,
        target: 600,
        xp: 800,
      }),
    ],
    bonusRules: HABIT_BONUSES,
    completionXp: 1500,
    completionCoins: 220,
    emblemKey: 'ach_track_language_streak',
    durationDays: 40,
    featuredRank: 76,
    tags: ['kopf', 'streak', 'skill'],
    swappableObjectiveIds: [],
    relapseMetric: null,
    relapseCopy: null,
  },
  {
    kind: TrackKind.CHALLENGE,
    slug: 'ch_mindfulness',
    title: 'Kopf frei',
    tagline: 'Zehn Minuten am Tag nichts tun — absichtlich.',
    description:
      'Meditation, Atemübung oder einfach still sitzen. Die Challenge für alle, deren Kopf ' +
      'nie aufhört zu reden.',
    emoji: '🧘',
    color: '#06b6d4',
    category: Category.MYSTERY,
    difficulty: Difficulty.EASY,
    objectives: [
      obj({
        id: 'o_mind_streak',
        title: 'Einundzwanzig Tage',
        description: 'Drei Wochen hintereinander eine Session.',
        emoji: '🌀',
        kind: ObjectiveKind.STREAK,
        metric: Metric.MINDFUL_MINUTES,
        target: 21,
        xp: 800,
      }),
      obj({
        id: 'o_mind_300',
        title: 'Fünf Stunden Stille',
        description: 'Insgesamt 300 Minuten.',
        emoji: '🕊️',
        kind: ObjectiveKind.THRESHOLD,
        metric: Metric.MINDFUL_MINUTES,
        target: 300,
        xp: 600,
      }),
    ],
    bonusRules: [
      ...HABIT_BONUSES,
      bonus('b_mind_morning', 'Vor 8 Uhr meditiert', BonusTrigger.BEFORE_HOUR, 8, 25),
    ],
    completionXp: 1000,
    completionCoins: 150,
    emblemKey: 'ach_track_mindfulness',
    durationDays: 30,
    featuredRank: 71,
    tags: ['kopf', 'gesundheit', 'streak'],
    swappableObjectiveIds: [],
    relapseMetric: null,
    relapseCopy: null,
  },
  {
    kind: TrackKind.CHALLENGE,
    slug: 'ch_social_reconnect',
    title: 'Wieder melden',
    tagline: 'Zwanzig Menschen, die sich freuen werden.',
    description:
      'Jeden Tag eine Person, mit der du zu lange nicht gesprochen hast. Kein großes Ding — ' +
      'eine Nachricht reicht. Die Reaktionen sind der eigentliche Lohn.',
    emoji: '💬',
    color: '#3b82f6',
    category: Category.SOCIAL,
    difficulty: Difficulty.EASY,
    objectives: [
      obj({
        id: 'o_social_20',
        title: 'Zwanzig Kontakte',
        description: 'Zwanzigmal jemanden anschreiben oder anrufen.',
        emoji: '📞',
        kind: ObjectiveKind.TALLY,
        metric: Metric.SOCIAL_CONTACT,
        target: 20,
        xp: 700,
      }),
      obj({
        id: 'o_social_streak',
        title: 'Zehn Tage am Stück',
        description: 'Zehn Tage hintereinander mindestens eine Person.',
        emoji: '🔥',
        kind: ObjectiveKind.STREAK,
        metric: Metric.SOCIAL_CONTACT,
        target: 10,
        xp: 500,
      }),
    ],
    bonusRules: HABIT_BONUSES,
    completionXp: 1000,
    completionCoins: 150,
    emblemKey: 'ach_track_social_reconnect',
    durationDays: 30,
    featuredRank: 75,
    tags: ['social', 'streak'],
    swappableObjectiveIds: [],
    relapseMetric: null,
    relapseCopy: null,
  },
  {
    kind: TrackKind.CHALLENGE,
    slug: 'ch_plogging',
    title: 'Plogging',
    tagline: 'Joggen und dabei Müll sammeln.',
    description:
      'Der schwedische Trend, der Sport und Aufräumen verbindet. Deine Runde wird dadurch ' +
      'langsamer und deine Nachbarschaft sauberer.',
    emoji: '♻️',
    color: '#16a34a',
    category: Category.ADVENTURE,
    difficulty: Difficulty.EASY,
    objectives: [
      obj({
        id: 'o_plog_100',
        title: 'Hundert Teile',
        description: 'Insgesamt 100 Stück Müll einsammeln.',
        emoji: '🗑️',
        kind: ObjectiveKind.THRESHOLD,
        metric: Metric.LITTER_COLLECTED,
        target: 100,
        xp: 800,
      }),
      obj({
        id: 'o_plog_routes',
        title: 'Zehn Runden',
        description: 'Zehnmal eine Plogging-Route laufen.',
        emoji: '🏃',
        kind: ObjectiveKind.TALLY,
        metric: Metric.ROUTE_COMPLETED,
        target: 10,
        xp: 600,
      }),
    ],
    bonusRules: [
      ...HABIT_BONUSES,
      bonus('b_plog_together', 'Zu zweit gesammelt', BonusTrigger.WITH_COMPANION, 1, 80),
    ],
    completionXp: 1200,
    completionCoins: 200,
    emblemKey: 'ach_track_plogging',
    durationDays: 45,
    featuredRank: 77,
    tags: ['draußen', 'gutes-tun', 'hype'],
    swappableObjectiveIds: [],
    relapseMetric: null,
    relapseCopy: null,
  },
  {
    kind: TrackKind.CHALLENGE,
    slug: 'ch_driving_theory',
    title: 'Führerschein-Theorie',
    tagline: 'Durchziehen statt aufschieben.',
    description:
      'Die Theorieprüfung scheitert nie am Wissen, sondern am Anfangen. Zwanzig Lernsessions, ' +
      'und du gehst vorbereitet rein.',
    emoji: '🚗',
    color: '#0891b2',
    category: Category.SKILL,
    difficulty: Difficulty.MEDIUM,
    objectives: [
      obj({
        id: 'o_theory_20',
        title: 'Zwanzig Sessions',
        description: 'Zwanzigmal Theorie lernen.',
        emoji: '📝',
        kind: ObjectiveKind.TALLY,
        metric: Metric.STUDY_MINUTES,
        target: 20,
        xp: 700,
      }),
      obj({
        id: 'o_theory_streak',
        title: 'Zwei Wochen dran',
        description: 'Vierzehn Tage hintereinander lernen.',
        emoji: '🔥',
        kind: ObjectiveKind.STREAK,
        metric: Metric.STUDY_MINUTES,
        target: 14,
        xp: 700,
      }),
    ],
    bonusRules: HABIT_BONUSES,
    completionXp: 1400,
    completionCoins: 250,
    emblemKey: 'ach_track_driving_theory',
    durationDays: 45,
    featuredRank: 81,
    tags: ['zukunft', 'schule'],
    swappableObjectiveIds: [],
    relapseMetric: null,
    relapseCopy: null,
  },
  {
    kind: TrackKind.CHALLENGE,
    slug: 'ch_sober_month',
    title: 'Nüchterner Monat',
    tagline: 'Dry January — an jedem beliebigen Monat.',
    description:
      'Dreißig Tage ohne Alkohol. Schlaf, Haut, Kontostand und Kopf melden sich alle vier ' +
      'innerhalb der ersten Woche zurück.',
    emoji: '🚱',
    color: '#7c3aed',
    category: Category.SKILL,
    difficulty: Difficulty.MEDIUM,
    objectives: [
      obj({
        id: 'o_sober_30',
        title: 'Dreißig Tage',
        description: 'Einen Monat am Stück ohne Alkohol.',
        emoji: '📆',
        kind: ObjectiveKind.STREAK,
        metric: Metric.ALCOHOL_FREE_DAY,
        target: 30,
        xp: 1500,
      }),
      obj({
        id: 'o_sober_saved',
        title: 'Was du nicht ausgegeben hast',
        description: 'Leg 80 € zurück, die sonst an der Bar geblieben wären.',
        emoji: '💶',
        kind: ObjectiveKind.THRESHOLD,
        metric: Metric.MONEY_SAVED,
        target: 80,
        xp: 400,
        optional: true,
      }),
    ],
    bonusRules: HABIT_BONUSES,
    completionXp: 1800,
    completionCoins: 300,
    emblemKey: 'ach_track_sober_month',
    durationDays: 35,
    featuredRank: 89,
    tags: ['hype', 'gesundheit', 'streak'],
    swappableObjectiveIds: [],
    relapseMetric: null,
    relapseCopy: null,
  },
  {
    kind: TrackKind.CHALLENGE,
    slug: 'ch_explorer',
    title: 'Stadt-Entdecker',
    tagline: 'Zwanzig Orte, an denen du noch nie warst.',
    description:
      'Du kennst deine Stadt nicht so gut, wie du denkst. Zwanzig neue Orte, alle in Laufweite, ' +
      'alle umsonst.',
    emoji: '🗺️',
    color: '#d97706',
    category: Category.ADVENTURE,
    difficulty: Difficulty.EASY,
    objectives: [
      obj({
        id: 'o_explore_20',
        title: 'Zwanzig neue Orte',
        description: 'An zwanzig unbekannten Orten einchecken.',
        emoji: '📍',
        kind: ObjectiveKind.TALLY,
        metric: Metric.PLACE_CHECKIN,
        target: 20,
        xp: 900,
      }),
      obj({
        id: 'o_explore_routes',
        title: 'Auf eigenen Wegen',
        description: 'Zehn Routen zu neuen Orten laufen.',
        emoji: '🧭',
        kind: ObjectiveKind.TALLY,
        metric: Metric.ROUTE_COMPLETED,
        target: 10,
        xp: 500,
        optional: true,
      }),
    ],
    bonusRules: [
      ...HABIT_BONUSES,
      bonus('b_explore_weekend', 'Am Wochenende erkundet', BonusTrigger.WEEKEND, 1, 30),
    ],
    completionXp: 1300,
    completionCoins: 220,
    emblemKey: 'ach_track_explorer',
    durationDays: 60,
    featuredRank: 73,
    tags: ['draußen', 'abenteuer'],
    swappableObjectiveIds: [],
    relapseMetric: null,
    relapseCopy: null,
  },
  {
    kind: TrackKind.CHALLENGE,
    slug: 'ch_daily_perfect',
    title: 'Perfekte Woche',
    tagline: 'Sieben Tage, alle Tagesquests erledigt.',
    description:
      'Die Meta-Challenge: räum sieben Tage hintereinander dein komplettes Tagesboard ab. ' +
      'Klingt einfach. Ist es an Tag fünf nicht mehr.',
    emoji: '✅',
    color: '#10b981',
    category: Category.SKILL,
    difficulty: Difficulty.MEDIUM,
    objectives: [
      obj({
        id: 'o_board_7',
        title: 'Sieben perfekte Tage',
        description: 'Sieben Tage hintereinander alle drei Tagesquests schaffen.',
        emoji: '🔥',
        kind: ObjectiveKind.STREAK,
        metric: Metric.DAILY_BOARD_CLEARED,
        target: 7,
        xp: 800,
      }),
      obj({
        id: 'o_board_30',
        title: 'Dreißig perfekte Tage',
        description: 'Für die, denen sieben zu leicht war.',
        emoji: '👑',
        kind: ObjectiveKind.STREAK,
        metric: Metric.DAILY_BOARD_CLEARED,
        target: 30,
        xp: 2500,
        optional: true,
      }),
    ],
    bonusRules: HABIT_BONUSES,
    completionXp: 1200,
    completionCoins: 200,
    emblemKey: 'ach_track_daily_perfect',
    durationDays: null,
    featuredRank: 93,
    tags: ['meta', 'streak', 'hype'],
    swappableObjectiveIds: [],
    relapseMetric: null,
    relapseCopy: null,
  },
];

export function getChallengeDef(slug: string): ChallengeDef | undefined {
  return CHALLENGE_CATALOG.find((c) => c.slug === slug);
}
